### PR TITLE
Group chat UI

### PR DESCRIPTION
**Pull request by KemoPaw**
**What this PR does** 📖
Change the icons in the Group Chat Aisle to match the UI/UX design.
https://satellite-im.atlassian.net/browse/AP-66

**Which issue(s) this PR fixes** 🔨

Fixes #

**Special notes for reviewers** 🗒️

**Additional comments** 🎤

### CODE REVIEW

**Review by WanderingHogan — APPROVED** [review]
perfect

**Review by stavares843 — CHANGES_REQUESTED** [review]
Captura de ecrã 2021-11-20, às 21 03 04

1. the icons are not the exact same compared with the ticket

on top are the ticket ones, on the bottom are the ones with the code from this branch

did the design change meanwhile? happy to merge like this if that's the intended design

2. also, the ticket mentions it's expected to show a copy when hovering the icons, at this moment, hovering the icons doesn't display any copy

**Comment by WanderingHogan** [comment]
@stavares843 good call on the text, icons I believe she ran the changes by Liz, and is using what we have access to here https://vue-feather-icons.egoist.sh/

**Comment by stavares843** [comment]
thanks for clarifying about the icons! so it's only the text stuff to check about @KemoPaw

**Comment by KemoPaw** [comment]
> thanks for clarifying about the icons! so it's only the text stuff to check about @KemoPaw

Hello @stavares843 , I just implemented the text changes for whenever you are available!

**Comment by stavares843** [comment]
thanks! 🎉 checking

**Review by stavares843 — APPROVED** [review]
approved ✅

**Review by WanderingHogan — APPROVED** [review]

**Pull request merged**
