### PR TITLE
Fix(iOSFitScreen): Fix app doesn't fit to screen SA-298

### PR DESCRIPTION
**Pull request by nickjjang**
Fixed friends box overlaying stream box in the sidebar

### CODE REVIEW

**Comment by WanderingHogan** [comment]
I can't actually tell what this is doing. I think what @phillsatellite  is going for in the ticket is really a change to the pwa config, like found here: https://medium.com/appscope/changing-the-ios-status-bar-of-your-progressive-web-app-9fc8fbe8e6ab with the `black-translucent` setting.

I think this is some combination of the meta part of the PWA module (https://pwa.nuxtjs.org/meta) and the manifest part (docs can be found on the same page).

In out code the manifest is set in the nuxt.config.js file

Also - does this ticket address other issues? It looks like you modified the scrolling to some places, but I can't actually get to them on ios because of another issue - unrelated to anything you've done. Something in the textile libraries that dm's dont work on iphones that we should open a ticket for.

**Review by WanderingHogan — APPROVED** [review]
great!

**Comment by WanderingHogan** [comment]
Screen Shot 2021-11-22 at 2 51 57 PM

**Review by genie-magic — APPROVED** [review]

**Comment by nickjjang** [comment]
Hi @stavares843 
Can you review and merge the current requests?
Thanks
Nick

**Comment by stavares843** [comment]
checking 🎉

**Review by stavares843 — APPROVED** [review]
approved ✅

**Pull request merged**
